// filepath: h:\WorkFolder\DoctrineFYP\boutique\frontend\src\dummyData.js
export const dummyCategories = [
  { _id: "cat1", name: "Dresses", image: "/placeholder.svg?text=Dresses" },
  { _id: "cat2", name: "Tops", image: "/placeholder.svg?text=Tops" },
  { _id: "cat3", name: "Bottoms", image: "/placeholder.svg?text=Bottoms" },
  { _id: "cat4", name: "Accessories", image: "/placeholder.svg?text=Accessories" },
  { _id: "cat5", name: "Shoes", image: "/placeholder.svg?text=Shoes" },
]

export const dummyProducts = [
  {
    _id: "prod1",
    name: "Elegant Floral Dress",
    description: "A beautiful floral dress perfect for summer evenings.",
    price: 79.99,
    image: "/placeholder.svg?text=Floral+Dress",
    category: "Dresses",
    inStock: true,
    featured: true,
    createdAt: new Date("2025-04-28T10:00:00Z"),
  },
  {
    _id: "prod2",
    name: "Casual Striped Top",
    description: "Comfortable and stylish striped top for everyday wear.",
    price: 29.99,
    image: "/placeholder.svg?text=Striped+Top",
    category: "Tops",
    inStock: true,
    featured: true,
    createdAt: new Date("2025-04-27T11:00:00Z"),
  },
  {
    _id: "prod3",
    name: "Classic Denim Jeans",
    description: "High-quality denim jeans with a classic fit.",
    price: 59.99,
    image: "/placeholder.svg?text=Denim+Jeans",
    category: "Bottoms",
    inStock: false,
    featured: false,
    createdAt: new Date("2025-04-26T12:00:00Z"),
  },
  {
    _id: "prod4",
    name: "Leather Crossbody Bag",
    description: "Stylish and practical leather crossbody bag.",
    price: 120.0,
    image: "/placeholder.svg?text=Leather+Bag",
    category: "Accessories",
    inStock: true,
    featured: true,
    createdAt: new Date("2025-04-25T13:00:00Z"),
  },
  {
    _id: "prod5",
    name: "Comfortable Sneakers",
    description: "Lightweight and comfortable sneakers for daily use.",
    price: 89.99,
    image: "/placeholder.svg?text=Sneakers",
    category: "Shoes",
    inStock: true,
    featured: false,
    createdAt: new Date("2025-04-24T14:00:00Z"),
  },
  {
    _id: "prod6",
    name: "Summer Maxi Dress",
    description: "Flowy maxi dress, perfect for warm weather.",
    price: 95.5,
    image: "/placeholder.svg?text=Maxi+Dress",
    category: "Dresses",
    inStock: true,
    featured: true,
    createdAt: new Date("2025-04-23T15:00:00Z"),
  },
  {
    _id: "prod7",
    name: "Silk Blouse",
    description: "Elegant silk blouse for formal occasions.",
    price: 65.0,
    image: "/placeholder.svg?text=Silk+Blouse",
    category: "Tops",
    inStock: true,
    featured: false,
    createdAt: new Date("2025-04-22T16:00:00Z"),
  },
  {
    _id: "prod8",
    name: "Tailored Trousers",
    description: "Smart tailored trousers for a professional look.",
    price: 75.0,
    image: "/placeholder.svg?text=Trousers",
    category: "Bottoms",
    inStock: true,
    featured: true,
    createdAt: new Date("2025-04-21T17:00:00Z"),
  },
  // Add more dummy products as needed
]

export const dummyOrders = [
  {
    _id: "order1",
    userId: "user123", // Replace with a relevant ID if needed for testing logged-in user
    items: [
      { productId: "prod1", name: "Elegant Floral Dress", price: 79.99, quantity: 1 },
      { productId: "prod4", name: "Leather Crossbody Bag", price: 120.0, quantity: 1 },
    ],
    shippingAddress: {
      fullName: "Jane Doe",
      address: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "12345",
      country: "USA",
    },
    paymentMethod: "Credit Card",
    totalAmount: 199.99,
    status: "Delivered",
    createdAt: new Date("2025-04-15T09:30:00Z"),
  },
  {
    _id: "order2",
    userId: "user123",
    items: [{ productId: "prod2", name: "Casual Striped Top", price: 29.99, quantity: 2 }],
    shippingAddress: {
      fullName: "Jane Doe",
      address: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "12345",
      country: "USA",
    },
    paymentMethod: "PayPal",
    totalAmount: 59.98,
    status: "Shipped",
    createdAt: new Date("2025-04-20T14:00:00Z"),
  },
]